# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.srcs/sources_1/ip/xxv_ethernet_0/xxv_ethernet_0.xci
# IP: The module: 'xxv_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.srcs/sources_1/ip/xxv_ethernet_0/xxv_ethernet_0.xci
# IP: The module: 'xxv_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lskje/Desktop/FPGA_Orderbook/orderbookproj/orderbookproj.gen/sources_1/ip/xxv_ethernet_0/synth/xxv_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xxv_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
